language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - python -m unittest discover intro
  - python -m unittest discover project
  - python -m unittest discover project_flask
